### ISSUE TITLE
Send parameter from php

### ISSUE THREAD

**Issue by williamsony** [spacexnu/PHP-JasperServer-Integration#2]
The code is perfect, now I need to send parameters from php to report you can help me a little

**Comment by alekir66** [comment]
$jasper->run('/reports/User/byId', 'XLS', array(
        'idUser' => '0603091737'
    ));

**Comment by williamsony** [comment]
Thanks for the reply. Now as the report language change ?. In the report designer I have it in Spanish but to display things like dates appears in English.

**Comment by alekir66** [comment]
@williamsony your last question is not related about this project and also is not related to this issue. You can search about your question in the web, for example [in jaspersoft community forums](http://community.jaspersoft.com/questions/800356/how-customize-input-controls-language-and-messages-jasperreports-471) [are a lot of articles, questions and answers about your question](http://community.jaspersoft.com/questions/537034/forcing-new-date-be-printed-specific-language). Please close this issue
